# Generated by Django 6.0 on 2025-12-17 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_photo_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GalleryPhoto',
        ),
    ]
